title: Saga bil

email: post@sagabil.no
description: > # this means to ignore newlines until "baseurl:"
  Salg av bruktbiler
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sagabil.no" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
  - Gemfile
  - Gemfile.lock
